### ISSUE TITLE
Errors from synopsis

### ISSUE THREAD

**Issue by librasteve** [rawleyfowler/Monad-Result#1]
Hi

I have tried to run the README synopsis, but getting multiple errors.

The first one is 
Type 'Result' is not declared

Sorry, without that working, I cannot really work out what is going on ... but would like to use the module

**Comment by rawleyfowler** [comment]
I just updated the README, sorry, that was a typo. This package is an implementation of a [monad](https://en.wikipedia.org/wiki/Monad_(functional_programming)), basically a computation with a side-effect, that is hidden.

**Comment by librasteve** [comment]
OK thanks!! - but now there is another error ;-)

Two terms in a row across lines (missing semicolon or comma?)

------> t.error('Bad value!') if $value eq 'bad'⏏<EOL>
    expecting any of:
        infix
        infix stopper

**Comment by rawleyfowler** [comment]
Another typo, missing semicolon. I probably should have written this synopsis in an editor instead of on Github :P

**Comment by rawleyfowler** [comment]
@librasteve Please let me know if there is anything else I can do to close this issue. Thanks!

**Comment by librasteve** [comment]
sorry - yes that's all good - thanks!
